"""Items table created

Revision ID: 3481e9a639e3
Revises: 
Create Date: 2019-09-19 17:02:27.082369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3481e9a639e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('retail_price', sa.Float(precision=2), nullable=False),
    sa.Column('wholesale_price', sa.Float(precision=2), nullable=False),
    sa.Column('discount', sa.Float(precision=2), nullable=True),
    sa.Column('mfd_date', sa.DateTime(), nullable=False),
    sa.Column('exp_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
