"""Payment table created

Revision ID: c392172a3ef7
Revises: 3b4008d6dbc6
Create Date: 2019-09-20 00:24:52.992656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c392172a3ef7'
down_revision = '3b4008d6dbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('payment_types',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('payments',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('id_payment_type', sa.Integer(), nullable=False),
    sa.Column('id_payment_method', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_payment_method'], ['payment_methods.id_'], ),
    sa.ForeignKeyConstraint(['id_payment_type'], ['payment_types.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('payment_types')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
